stage1:
  base_lr: 0.00005
  disc_lr: 0.0001
  perceptual_weight: 0.002
  adv_weight: 0.005
  params:
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    num_channels: [64, 128, 128, 128]
    num_res_layers: 2
    downsample_parameters: [[2, 4, 1, 1], [2, 4, 1, 1], [2, 4, 1, 1]]
    upsample_parameters: [[2, 4, 1, 1, 0], [2, 4, 1, 1, 0], [2, 4, 1, 1, 0]]
    num_embeddings: 256
    embedding_dim: 32

discriminator:
  params:
    spatial_dims: 2
    num_channels: 64
    num_layers_d: 3
    in_channels: 1
    out_channels: 1

perceptual_network:
  params:
    spatial_dims: 2
    network_type: "squeeze"
